name: Fetch and Download
on:
  workflow_dispatch:
jobs:
  fetch_and_download:
    name: Fetch and Download
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with: 
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
        cp ./settings_profiles/settings_github_workflow.yaml ./settings.yaml
    - name: Fetch
      run: |
        python ./main.py
    - name: Zip Files
      run: |
        zip -r ./data.zip ./data
    - name: Upload
      env:
        PRIVATE_KEY: ${{ secrets.ID_RSA_LS }}
      run: |
        echo "$PRIVATE_KEY" >> ./id_rsa_ls
        chmod 600 ./id_rsa_ls
        scp -P 14122 -i ./id_rsa_ls -o StrictHostKeyChecking=no ./data.zip root@hwpo.top:/home/wwwroot/drive/data/lucien/files/clash/public/
        echo "download at: https://drive.hwpo.top/s/Gq88PciGDpRR4Yq"
